import { createContext, useState } from "react"
import banner_01 from "../assets/images/banner-01.jpg"
import banner_02 from "../assets/images/banner-02.jpg"
import banner_03 from "../assets/images/banner-03.jpg"
import banner_04 from "../assets/images/banner-04.jpg"
import banner_05 from "../assets/images/banner-05.jpg"
import banner_06 from "../assets/images/banner-06.jpg"
import banner_07 from "../assets/images/banner-07.jpg"
import banner_08 from "../assets/images/banner-08.jpg"
import banner_09 from "../assets/images/banner-09.jpg"
import banner_10 from "../assets/images/banner-10.jpg"
import banner_11 from "../assets/images/banner-11.jpg"
import banner_12 from "../assets/images/banner-12.jpg"
import banner_13 from "../assets/images/banner-13.jpg"
import banner_14 from "../assets/images/banner-14.jpg"
import blog_01 from "../assets/images/blog-01.jpg"
import blog_02 from "../assets/images/blog-02.jpg"
import blog_03 from "../assets/images/blog-03.jpg"
import blog_04 from "../assets/images/blog-04.jpg"
import blog_05 from "../assets/images/blog-05.jpg"
import blog_06 from "../assets/images/blog-06.jpg"
import blog_07 from "../assets/images/blog-07.jpg"
import blog_08 from "../assets/images/blog-08.jpg"
import blog_09 from "../assets/images/blog-09.jpg"
import blog_10 from "../assets/images/blog-10.jpg"
import gallery_01 from "../assets/images/gallery-01.jpg"
import gallery_02 from "../assets/images/gallery-02.jpg"
import gallery_03 from "../assets/images/gallery-03.jpg"
import gallery_04 from "../assets/images/gallery-04.jpg"
import gallery_05 from "../assets/images/gallery-05.jpg"
import gallery_06 from "../assets/images/gallery-06.jpg"
import gallery_07 from "../assets/images/gallery-07.jpg"
import gallery_08 from "../assets/images/gallery-08.jpg"
import gallery_09 from "../assets/images/gallery-09.jpg"
import gallery_10 from "../assets/images/gallery-10.jpg"
import gallery_11 from "../assets/images/gallery-11.jpg"
import gallery_12 from "../assets/images/gallery-12.jpg"
import gallery_13 from "../assets/images/gallery-13.jpg"
import gallery_14 from "../assets/images/gallery-14.jpg"
import gallery_15 from "../assets/images/gallery-15.jpg"
import item_01 from "../assets/images/item-01.jpg"
import item_02 from "../assets/images/item-02.jpg"
import item_03 from "../assets/images/item-03.jpg"
import item_04 from "../assets/images/item-04.jpg"
import item_05 from "../assets/images/item-05.jpg"
import item_06 from "../assets/images/item-06.jpg"
import item_07 from "../assets/images/item-07.jpg"
import item_08 from "../assets/images/item-08.jpg"
import item_09 from "../assets/images/item-09.jpg"
import item_10 from "../assets/images/item-10.jpg"
import item_11 from "../assets/images/item-11.jpg"
import item_12 from "../assets/images/item-12.jpg"
import item_13 from "../assets/images/item-13.jpg"
import item_14 from "../assets/images/item-14.jpg"
import item_15 from "../assets/images/item-15.jpg"
import item_16 from "../assets/images/item-16.jpg"
import item_17 from "../assets/images/item-17.jpg"
import item_cart_01 from "../assets/images/item-cart-01.jpg"
import item_cart_02 from "../assets/images/item-cart-02.jpg"
import item_cart_03 from "../assets/images/item-cart-03.jpg"
import item_cart_04 from "../assets/images/item-cart-04.jpg"
import item_cart_05 from "../assets/images/item-cart-05.jpg"
import item_cart_06 from "../assets/images/item-cart-06.jpg"
import master_slide_07 from "../assets/images/master-slide-07.jpg"
import master_slide_08 from "../assets/images/master-slide-08.jpg"
import product_detail_01 from "../assets/images/product-detail-01.jpg"
import product_detail_02 from "../assets/images/product-detail-02.jpg"
import product_detail_03 from "../assets/images/product-detail-03.jpg"
import shop_item_09 from "../assets/images/shop-item-09.jpg"
import thumb_item_01 from "../assets/images/thumb-item-01.jpg"
import thumb_item_02 from "../assets/images/thumb-item-02.jpg"
import thumb_item_03 from "../assets/images/thumb-item-03.jpg"

export const MyContext = createContext()
export const ContextProvider = ({ children }) => {

    const [storeDataBase, setStoreDataBase] = useState([
        {

            id: 1,
            productName: 'Elegant Evening Dress',
            productImage: banner_01,
            productImages: [],
            productCategorie: 'women',
            productPrice: 39.99,
            productType: 'dress',
            productDescription: 'Turn heads with this elegant evening dress for special occasions.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 2,
            productName: 'Vintage Lace Midi Dress',
            productImage: banner_02,
            productImages: [],
            productCategorie: 'women',
            productPrice: 69.99,
            productType: 'dress',
            productDescription: 'Step out in style with this vintage lace midi dress for a classic look.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 3,
            productName: 'Luxury Chronograph Watch',
            productImage: banner_03,
            productImages: [],
            productCategorie: 'men',
            productPrice: 129.99,
            productType: 'watch',
            productDescription: 'Indulge in luxury with this chronograph watch for a refined timepiece.',
            productState: 'sale',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 4,
            productName: 'Modern Tech back_pack',
            productImage: banner_04,
            productImages: [],
            productCategorie: 'men',
            productPrice: 79.99,
            productType: 'back_pack',
            productDescription: 'Stay organized and stylish with this modern tech back_pack for daily use.',
            productState: 'new',
            size: ['M', 'L'],
            sizeSelected: ``,
        },
        {
            id: 5,
            productName: 'Chic Cat-Eye glasses',
            productImage: banner_05,
            productImages: [],
            productCategorie: 'women',
            productPrice: 59.99,
            productType: 'glasses',
            productDescription: 'Enhance your style with these chic cat-eye glasses for a trendy look.',
            productState: 'new',
            size: ['M', 'L'],
            sizeSelected: ``,
        },
        {
            id: 6,
            productName: 'Slim Fit Distressed Jeans',
            productImage: banner_06,
            productImages: [],
            productCategorie: 'men',
            productPrice: 89.99,
            productType: 'jean',
            productDescription: 'Achieve a rugged yet stylish look with these slim-fit distressed jeans.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 7,
            productName: 'Fashion Sneakers',
            productImage: banner_07,
            productImages: [],
            productCategorie: 'women',
            productPrice: 79.99,
            productType: 'shoes',
            productDescription: 'Step out in comfort and style with these fashionable sneakers.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 8,
            productName: 'Graphic Print Tee',
            productImage: banner_08,
            productImages: [],
            productCategorie: 'women',
            productPrice: 49.99,
            productType: 't-shirt',
            productDescription: 'Make a statement with this graphic print tee for a trendy casual look.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 9,
            productName: 'Stylish Aviator Glasses',
            productImage: banner_09,
            productImages: [],
            productCategorie: 'men',
            productPrice: 79.99,
            productType: 'glasses',
            productDescription: 'Channel your inner pilot with these stylish aviator glasses for a bold look.',
            productState: 'old',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 10,
            productName: 'Urban Explorer back_pack',
            productImage: banner_10,
            productImages: [],
            productCategorie: 'men',
            productPrice: 89.99,
            productType: 'back_pack',
            productDescription: 'Discover the city with this urban explorer back_pack for your daily adventures.',
            productState: 'sale',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 11,
            productName: 'Casual V-Neck Tee',
            productImage: banner_11,
            productImages: [],
            productCategorie: 'women',
            productPrice: 59.99,
            productType: 't-shirt',
            productDescription: 'Stay comfortable and chic with this casual V-neck tee for everyday wear.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 12,
            productName: 'Floral Print Maxi Dress',
            productImage: banner_12,
            productImages: [],
            productCategorie: 'women',
            productPrice: 99.99,
            productType: 'dress',
            productDescription: 'Embrace floral elegance with this maxi dress for a graceful appearance.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 13,
            productName: 'Chic Ruffle Sleeve Dress',
            productImage: banner_13,
            productImages: [],
            productCategorie: 'women',
            productPrice: 109.99,
            productType: 'dress',
            productDescription: 'Make a fashion statement with this chic ruffle sleeve dress for any occasion.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 14,
            productName: 'Classic Button-Up Shirt',
            productImage: banner_14,
            productImages: [],
            productCategorie: 'women',
            productPrice: 69.99,
            productType: 'shirt',
            productDescription: 'Elevate your wardrobe with this classic button-up shirt for a polished look.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 15,
            productName: 'Sleek Leather back_pack',
            productImage: blog_01,
            productImages: [],
            productCategorie: 'women',
            productPrice: 119.99,
            productType: 'back_pack',
            productDescription: 'Stay stylish and organized with this sleek leather back_pack for your essentials.',
            productState: 'sale',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 16,
            productName: 'Casual Striped Tee',
            productImage: blog_02,
            productImages: [],
            productCategorie: 'women',
            productPrice: 44.99,
            productType: 't-shirt',
            productDescription: 'Add a touch of stripes to your wardrobe with this casual striped tee.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 17,
            productName: 'Compact Travel back_pack',
            productImage: blog_03,
            productImages: [],
            productCategorie: 'women',
            productPrice: 29.99,
            productType: 'back_pack',
            productDescription: 'Travel light and stylish with this compact travel back_pack for your adventures.',
            productState: 'new',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 18,
            productName: 'Floral Print Midi Dress',
            productImage: blog_04,
            productImages: [],
            productCategorie: 'women',
            productPrice: 79.99,
            productType: 'dress',
            productDescription: 'Flaunt your feminine side with this floral print midi dress for a charming look.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 19,
            productName: 'Trendy Oversized glasses',
            productImage: blog_05,
            productImages: [],
            productCategorie: 'women',
            productPrice: 49.99,
            productType: 'glasses',
            productDescription: 'Stay on trend with these oversized glasses for a bold and glamorous style.',
            productState: 'old',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 20,
            productName: 'Vintage Graphic Tee',
            productImage: blog_06,
            productImages: [],
            productCategorie: 'women',
            productPrice: 34.99,
            productType: 't-shirt',
            productDescription: 'Show off your vintage vibes with this graphic tee for a casual and cool look.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 21,
            productName: 'Stylish Leather back_pack',
            productImage: blog_08,
            productImages: [],
            productCategorie: 'women',
            productPrice: 89.99,
            productType: 'back_pack',
            productDescription: 'Upgrade your style with this stylish leather back_pack for a fashion-forward statement.',
            productState: 'new',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 22,
            productName: 'Urban Explorer back_pack 2',
            productImage: blog_10,
            productImages: [],
            productCategorie: 'men',
            productPrice: 99.99,
            productType: 'back_pack',
            productDescription: 'Continue your urban exploration with this updated version of the popular back_pack.',
            productState: 'old',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 23,
            productName: 'Adventure-Ready back_pack',
            productImage: gallery_01,
            productImages: [],
            productCategorie: 'women',
            productPrice: 129.99,
            productType: 'back_pack',
            productDescription: 'Embark on your next adventure with this durable and adventure-ready back_pack.',
            productState: 'new',
            size: ['S', 'M', 'L'],
            sizeSelected: ``,
        },
        {
            id: 24,
            productName: 'Cropped Graphic Tee',
            productImage: gallery_02,
            productImages: [],
            productCategorie: 'women',
            productPrice: 54.99,
            productType: 't-shirt',
            productDescription: 'Add a trendy twist to your style with this cropped graphic tee for a bold statement.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 25,
            productName: 'white Dress',
            productImage: gallery_08,
            productImages: [],
            productCategorie: 'women',
            productPrice: 49.99,
            productType: 'dress',
            productDescription: 'Beautiful blue dress for any occasion.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 26,
            productName: 'Leather Jacket',
            productImage: gallery_04,
            productImages: [],
            productCategorie: 'men',
            productPrice: 79.99,
            productType: 'jacket',
            productDescription: 'Stylish leather jacket to keep you warm.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 27,
            productName: 'Casual T-Shirt',
            productImage: gallery_07,
            productImages: [],
            productCategorie: 'women',
            productPrice: 29.99,
            productType: 't-shirt',
            productDescription: 'Comfortable and casual t-shirt for everyday wear.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 28,
            productName: 'Running Shoes',
            productImage: gallery_15,
            productImages: [],
            productCategorie: 'men',
            productPrice: 59.99,
            productType: 'shoes',
            productDescription: 'Comfortable running shoes for your active lifestyle.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 29,
            productName: 'Elegant Ring',
            productImage: gallery_12,
            productImages: [],
            productCategorie: 'women',
            productPrice: 89.99,
            productType: 'ring',
            productDescription: 'Elegantly designed ring for special occasions.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 30,
            productName: 'Denim Jeans',
            productImage: gallery_14,
            productImages: [],
            productCategorie: 'men',
            productPrice: 69.99,
            productType: 'jeans',
            productDescription: 'Classic denim jeans for a timeless look.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 31,
            productName: 'glasses',
            productImage: shop_item_09,
            productImages: [],
            productCategorie: 'women',
            productPrice: 39.99,
            productType: 'glasses',
            productDescription: 'Stylish glasses to complete your look.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 32,
            productName: 'Graphic T-Shirt',
            productImage: gallery_07,
            productImages: [],
            productCategorie: 'men',
            productPrice: 34.99,
            productType: 't-shirt',
            productDescription: 'Bold graphic t-shirt for a statement look.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 33,
            productName: 'Smartwatch',
            productImage: item_08,
            productImages: [],
            productCategorie: 'women',
            productPrice: 129.99,
            productType: 'watch',
            productDescription: 'High-tech smartwatch for modern convenience.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 34,
            productName: 'Leather back_pack',
            productImage: item_02,
            productImages: [],
            productCategorie: 'men',
            productPrice: 109.99,
            productType: 'back_pack',
            productDescription: 'Durable leather back_pack for your daily essentials.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 35,
            productName: 'Running Shoes',
            productImage: item_17,
            productImages: [],
            productCategorie: 'men',
            productPrice: 59.99,
            productType: 'shoes',
            productDescription: 'Comfortable running shoes for your active lifestyle.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 36,
            productName: 'Classic Blue Jeans',
            productImage: item_12,
            productImages: [],
            productCategorie: 'men',
            productPrice: 49.99,
            productType: 'jeans',
            productDescription: 'Timeless classic blue jeans for a casual look.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 37,
            productName: 'Slim Fit Jeans',
            productImage: item_11,
            productImages: [],
            productCategorie: 'women',
            productPrice: 54.99,
            productType: 'jeans',
            productDescription: 'Slim fit jeans to highlight your silhouette.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 38,
            productName: 'Distressed Denim Jeans',
            productImage: item_13,
            productImages: [],
            productCategorie: 'men',
            productPrice: 59.99,
            productType: 'jeans',
            productDescription: 'Stylish distressed denim jeans for a rugged look.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 39,
            productName: 'High-Waisted Skinny Jeans',
            productImage: item_15,
            productImages: [],
            productCategorie: 'women',
            productPrice: 64.99,
            productType: 'jeans',
            productDescription: 'High-waisted skinny jeans for a modern fashion statement.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 40,
            productName: 'Relaxed Fit Denim Jeans',
            productImage: item_16,
            productImages: [],
            productCategorie: 'men',
            productPrice: 54.99,
            productType: 'jeans',
            productDescription: 'Comfortable relaxed fit denim jeans for everyday wear.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 41,
            productName: 'Graphic Print T-Shirt',
            productImage: product_detail_03,
            productImages: [],
            productCategorie: 'women',
            productPrice: 24.99,
            productType: 't-shirt',
            productDescription: 'Stylish graphic print t-shirt for a trendy look.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 42,
            productName: 'Striped Cotton T-Shirt',
            productImage: thumb_item_01,
            productImages: [],
            productCategorie: 'women',
            productPrice: 19.99,
            productType: 't-shirt',
            productDescription: 'Comfortable striped cotton t-shirt for everyday wear.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 43,
            productName: 'V-Neck Casual Tee',
            productImage: thumb_item_02,
            productImages: [],
            productCategorie: 'women',
            productPrice: 29.99,
            productType: 't-shirt',
            productDescription: 'Casual V-neck tee for a relaxed and stylish look.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 44,
            productName: 'Basic Crewneck T-Shirt',
            productImage: thumb_item_03,
            productImages: [],
            productCategorie: 'women',
            productPrice: 22.99,
            productType: 't-shirt',
            productDescription: 'Basic crewneck t-shirt for versatile everyday styling.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 45,
            productName: 'Adventure Seeker back_pack',
            productImage: gallery_09,
            productImages: [],
            productCategorie: 'women',
            productPrice: 79.99,
            productType: 'back_pack',
            productDescription: 'Spacious adventure seeker back_pack for the modern explorer.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 46,
            productName: 'Fashionable Travel back_pack',
            productImage: gallery_13,
            productImages: [],
            productCategorie: 'women',
            productPrice: 99.99,
            productType: 'back_pack',
            productDescription: 'Stylish and fashionable travel back_pack for your journeys.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },



        // ! --------------------

        {
            id: 47,
            productName: 'Chic Patterned Dress',
            productImage: item_03,
            productImages: [],
            productCategorie: 'women',
            productPrice: 69.99,
            productType: 'dress',
            productDescription: 'Make a statement with this chic patterned dress, perfect for a night out or special occasions.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 48,
            productName: 'Sleek Leather Boots',
            productImage: item_04,
            productImages: [],
            productCategorie: 'women',
            productPrice: 89.99,
            productType: 'shoes',
            productDescription: 'Step out in style with these sleek leather boots, a versatile addition to your footwear collection.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 49,
            productName: 'Casual Denim Jacket',
            productImage: item_05,
            productImages: [],
            productCategorie: 'men',
            productPrice: 59.99,
            productType: 'jean',
            productDescription: 'Enhance your casual look with this stylish denim jacket, a must-have for every wardrobe.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 50,
            productName: 'Elegant Silver Earrings',
            productImage: item_06,
            productImages: [],
            productCategorie: 'women',
            productPrice: 39.99,
            productType: 'jean',
            productDescription: 'Add a touch of elegance to your ensemble with these elegant silver earrings for a polished look.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 51,
            productName: 'Cozy Knit Beanie',
            productImage: item_07,
            productImages: [],
            productCategorie: 'men',
            productPrice: 24.99,
            productType: 'jean',
            productDescription: 'Stay warm and stylish with this cozy knit beanie, perfect for colder days.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 52,
            productName: 'Casual Striped Tee',
            productImage: item_01,
            productImages: [],
            productCategorie: 'men',
            productPrice: 34.99,
            productType: 't-shirt',
            productDescription: 'Add a touch of stripes to your casual wardrobe with this comfortable striped tee.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 53,
            productName: 'Vintage-Inspired back_pack',
            productImage: blog_07,
            productImages: [],
            productCategorie: 'women',
            productPrice: 74.99,
            productType: 'back_pack',
            productDescription: 'Embrace vintage charm with this vintage-inspired back_pack, a stylish and functional choice.',
            productState: 'sale',
            size: ['S', 'M'],
            sizeSelected: ``,
        },
        {
            id: 54,
            productName: 'Cozy Knit Scarf',
            productImage: blog_09,
            productImages: [],
            productCategorie: 'men',
            productPrice: 19.99,
            productType: 'jean',
            productDescription: 'Stay warm and fashionable with this cozy knit scarf, an essential accessory for the winter season.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 55,
            productName: 'Casual Striped T-Shirt',
            productImage: item_cart_01,
            productImages: [],
            productCategorie: 'men',
            productPrice: 29.99,
            productType: 't-shirt',
            productDescription: 'Keep it casual with this striped t-shirt, perfect for everyday wear and comfort.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 56,
            productName: 'Leather Crossbody back_pack',
            productImage: item_cart_02,
            productImages: [],
            productCategorie: 'women',
            productPrice: 49.99,
            productType: 'back_pack',
            productDescription: 'Stay organized and stylish with this leather crossbody back_pack, a perfect accessory for any occasion.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 57,
            productName: 'Modern Watch',
            productImage: item_cart_03,
            productImages: [],
            productCategorie: 'men',
            productPrice: 79.99,
            productType: 'watch',
            productDescription: 'Upgrade your wristwear with this modern and sleek watch, perfect for any formal or casual ensemble.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 58,
            productName: 'Cozy Hooded Sweatshirt',
            productImage: item_cart_04,
            productImages: [],
            productCategorie: 'men',
            productPrice: 39.99,
            productType: 't-shirt',
            productDescription: 'Stay warm and comfortable in this cozy hooded sweatshirt, ideal for chilly days.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 59,
            productName: 'Stylish glasses',
            productImage: item_cart_05,
            productImages: [],
            productCategorie: 'women',
            productPrice: 29.99,
            productType: 'glasses',
            productDescription: 'Add a touch of style to your look with these chic and stylish glasses, perfect for sunny days.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 60,
            productName: 'Classic Denim Jeans',
            productImage: item_cart_06,
            productImages: [],
            productCategorie: 'men',
            productPrice: 54.99,
            productType: 'jeans',
            productDescription: 'Achieve a timeless look with these classic denim jeans, a wardrobe essential for every man.',
            productState: 'old',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,

        },
        {
            id: 61,
            productName: 'Stylish Leather shirt',
            productImage: master_slide_07,
            productImages: [],
            productCategorie: 'men',
            productPrice: 34.99,
            productType: 'shirt',
            productDescription: 'Complete your outfit with this stylish leather shirt, a versatile accessory for any occasion.',
            productState: 'sale',
            size: ['M', 'L', 'XL'],
            sizeSelected: ``,

        },
        {
            id: 62,
            productName: 'Chic Women\'s t-shirt',
            productImage: master_slide_08,
            productImages: [],
            productCategorie: 'women',
            productPrice: 44.99,
            productType: 't-shirt',
            productDescription: 'Elevate your style with this chic women\'s t-shirt, perfect for both casual and formal occasions.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL'],
            sizeSelected: ``,
        },
        {
            id: 63,
            productName: 'Modern Smartphone Stand',
            productImage: product_detail_01,
            productImages: [],
            productCategorie: 'electronics',
            productPrice: 19.99,
            productType: 'jean',
            productDescription: 'Keep your smartphone in place with this modern and sleek smartphone stand, perfect for your desk or bedside table.',
            productState: 'new',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
        {
            id: 64,
            productName: 'Wireless Earbuds',
            productImage: product_detail_02,
            productImages: [],
            productCategorie: 'electronics',
            productPrice: 69.99,
            productType: 'jean',
            productDescription: 'Enjoy wireless freedom with these stylish and high-quality wireless earbuds, perfect for music enthusiasts on the go.',
            productState: 'sale',
            size: ['S', 'M', 'L', 'XL', '2XL'],
            sizeSelected: ``,
        },
    ])

    const [cartDataBase, setCartDataBase] = useState([])
    const [customer, setCustomer] = useState([])

    console.log(customer);
    return (
        <>
            <MyContext.Provider value={{ customer, setCustomer, storeDataBase, setStoreDataBase, cartDataBase, setCartDataBase }}>
                {children}
            </MyContext.Provider>
        </>
    )
}